
const LANGUAGE_MESSAGE = {
  en: {
    conversationStartMessage: "Welcome! I’m MItra, and I’m here to collect your story of improvement. I’ve heard you and your community have done some amazing work, and I’d love to hear about it. To start, can you tell me your name?",
    conversationStartMessageForCaptureDiscussion: "Welcome! I’m MItra, and I’m here to capture the important points from your discussions. I know you and your community have shared valuable insights—both challenges and solutions. Before we get started, can you first tell me your name?",
    sessionReconnected: "Session reconnected! Please continue where you left off.",
    noPreviousSession: "Could not find your previous session. Please start a new one by typing 'Hi'.",
    errorMessage: "⚠️ Something went wrong. Type 'Hi' to start again.",
    sessionDiscontinue: "⚠️ Your session was disconnected.",
    reconnectMessage: "Would you like to *reconnect* to your existing session or start a *new one*?",
    inactiveSession: "Your session has been inactive for a while",
    reconnectPrompt: "Would you like to *continue* your current session or *start a new one*?",
    sessionCompleted: "Congratulations! You've completed your session. Type 'Hi' to start a new one.",
    maxPhotosWarning: "You've reached the maximum number of photos allowed",
    doneMessage: "Type *done* to generate your report",
    imageDownloadError: "Could not download the image. Please try again.",
    storyDownloadError: "Could not retrieve your story. Please try again.",
    imageUploadSuccess: "Image uploaded successfully!",
    remainingPhotos: "photo(s) remaining. You can send more photos/video or finish now..",
    addMorePhotos: "Add More Photos/videos",
    reportGenerationMessage: "photos uploaded! Generating your report...",
    downloadorEditReport: "Would you like to download the report or edit it?",
    reportRetrievalError: "Could not retrieve your report. Please try again.",
    editReportText: "*Edit your report",
    discussionRecorded: "Your discussion or story has been recorded!",
    uploadLimit: "You can upload up to",
    yesUpload: "Yes, Upload",
    evidenceLimit: "Please send your photos one by one (up to 10).",
    done: "Type *done* when you have finished uploading.",
    requestNextPhoto: "Please send your next photo.",
    lostSession: "Session lost. Please type 'Hi' to start again.",
    cancelEvidenceUpload: "Cancel Evidence Upload",
    cancelSession: "Cancelled. Type 'menu' to see options.",
    sessionLost: "Could not reconnect to your session. Returning to the main menu.",
    newSessionStarted: "Previous session cleared. Starting new session...",
    imageUploadFailed: "Failed to upload image. Please try again.",
    whatsappNotSupported: "Sorry, I can only handle text, voice, images, and interactive messages",
    notUnderstood: "Sorry, didn't understand that. Please type 'Hi' to see options or 'Menu' to see the main menu.",
    audioDownloadError: "Could not download the audio. Please try again.",
    wsSessionRequired: "Please respond with text/audio during an active session.",
    voiceProcessing: "Processing your voice message...",
    voiceHeard: "I heard:",
    voiceSendConfirm: "Send this message?",
    voiceEditPrompt: "✏️ Type your corrected message:",
    voiceRetryPrompt: "🔄 Please send your voice note again.",
    voiceSend: "✅ Send",
    voiceEdit: "✏️ Edit",
    voiceRetry: "🔄 Retry",
    voiceSent: "Message sent successfully.",
    voiceSendFailed: "Failed to send message. Please try again.",
    voiceNoPending: "No pending message found. Please send your voice note again.",
    voiceNoTranscript: "No transcript found to edit. Please send your voice note again.",
    languageSetup:"⏳ Setting up your language..."
  },
  kn: {
    conversationStartMessage: "ಸ್ವಾಗತ! ನಾನು ಮಿತ್ರ, ಮತ್ತು ನಾನು ನಿಮ್ಮ ಸುಧಾರಣೆಯ ಕಥೆಯನ್ನು ಸಂಗ್ರಹಿಸಲು ಇಲ್ಲಿದ್ದೇನೆ. ನೀವು ಮತ್ತು ನಿಮ್ಮ ಸಮುದಾಯವು ಕೆಲವು ಅದ್ಭುತ ಕೆಲಸಗಳನ್ನು ಮಾಡಿದ್ದೀರಿ ಎಂದು ನಾನು ಕೇಳಿದ್ದೇನೆ ಮತ್ತು ಅದರ ಬಗ್ಗೆ ಕೇಳಲು ನಾನು ಇಷ್ಟಪಡುತ್ತೇನೆ. ಪ್ರಾರಂಭಿಸಲು, ನಿಮ್ಮ ಹೆಸರನ್ನು ನನಗೆ ಹೇಳುವಿರಾ?",
    conversationStartMessageForCaptureDiscussion: "ಸ್ವಾಗತ! ನಾನು ಮಿತ್ರ, ನಿಮ್ಮ ಚರ್ಚೆಗಳಿಂದ ಪ್ರಮುಖ ಅಂಶಗಳನ್ನು ಸೆರೆಹಿಡಿಯಲು ನಾನಿಲ್ಲಿದ್ದೇನೆ. ನೀವು ಮತ್ತು ನಿಮ್ಮ ಸಮುದಾಯವು ಸವಾಲುಗಳು ಮತ್ತು ಪರಿಹಾರಗಳೆರಡರ ಬಗ್ಗೆಯೂ ಮೌಲ್ಯಯುತವಾದ ಒಳನೋಟಗಳನ್ನು ಹಂಚಿಕೊಂಡಿದ್ದೀರಿ ಎಂದು ನನಗೆ ತಿಳಿದಿದೆ. ನಾವು ಪ್ರಾರಂಭಿಸುವ ಮೊದಲು, ನಿಮ್ಮ ಹೆಸರನ್ನು ತಿಳಿಸುವಿರಾ?",
    sessionReconnected: "ಸೆಷನ್ ಮರುಸಂಪರ್ಕಗೊಂಡಿದೆ! ದಯವಿಟ್ಟು ನೀವು ನಿಲ್ಲಿಸಿದಲ್ಲಿಂದ ಮುಂದುವರಿಸಿ.",
    noPreviousSession: "ನಿಮ್ಮ ಹಿಂದಿನ ಸೆಷನ್ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು 'Hi' ಎಂದು ಟೈಪ್ ಮಾಡುವ ಮೂಲಕ ಹೊಸದನ್ನು ಪ್ರಾರಂಭಿಸಿ.",
    errorMessage: "⚠️ ಏನೋ ತಪ್ಪಾಗಿದೆ. ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಲು 'Hi' ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    sessionDiscontinue: "⚠️ ನಿಮ್ಮ ಸೆಷನ್ ಸಂಪರ್ಕ ಕಡಿತಗೊಂಡಿದೆ.",
    reconnectMessage: "ನಿಮ್ಮ ಅಸ್ತಿತ್ವದಲ್ಲಿರುವ ಸೆಷನ್‌ಗೆ *ಮರುಸಂಪರ್ಕಿಸಲು* ಅಥವಾ *ಹೊಸದನ್ನು* ಪ್ರಾರಂಭಿಸಲು ನೀವು ಬಯಸುವಿರಾ?",
    inactiveSession: "ನಿಮ್ಮ ಸೆಷನ್ ಸ್ವಲ್ಪ ಸಮಯದಿಂದ ನಿಷ್ಕ್ರಿಯವಾಗಿದೆ",
    reconnectPrompt: "ನಿಮ್ಮ ಪ್ರಸ್ತುತ ಸೆಷನ್ ಅನ್ನು *ಮುಂದುವರಿಸಲು* ಅಥವಾ *ಹೊಸದನ್ನು ಪ್ರಾರಂಭಿಸಲು* ನೀವು ಬಯಸುವಿರಾ?",
    sessionCompleted: "ಅಭಿನಂದನೆಗಳು! ನೀವು ನಿಮ್ಮ ಸೆಷನ್ ಅನ್ನು ಪೂರ್ಣಗೊಳಿಸಿದ್ದೀರಿ. ಹೊಸದನ್ನು ಪ್ರಾರಂಭಿಸಲು 'Hi' ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    maxPhotosWarning: "ನೀವು ಅನುಮತಿಸಲಾದ ಗರಿಷ್ಠ ಸಂಖ್ಯೆಯ ಫೋಟೋಗಳನ್ನು ತಲುಪಿದ್ದೀರಿ",
    doneMessage: "ನಿಮ್ಮ ವರದಿಯನ್ನು ರಚಿಸಲು *done* ಎಂದು ಟೈಪ್ ಮಾಡಿ",
    imageDownloadError: "ಚಿತ್ರವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
    storyDownloadError: "ನಿಮ್ಮ ಕಥೆಯನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
    imageUploadSuccess: "ಚಿತ್ರವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ!",
    remainingPhotos: "ಫೋಟೋ(ಗಳು) ಬಾಕಿ ಉಳಿದಿವೆ. ನೀವು ಹೆಚ್ಚಿನ ಫೋಟೋಗಳು/ವೀಡಿಯೊಗಳನ್ನು ಕಳುಹಿಸಬಹುದು ಅಥವಾ ಈಗ ಮುಗಿಸಬಹುದು..",
    addMorePhotos: "ಇನ್ನಷ್ಟು ಫೋಟೋಗಳು/ವೀಡಿಯೊಗಳನ್ನು ಸೇರಿಸಿ",
    reportGenerationMessage: "ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಿದೆ! ನಿಮ್ಮ ವರದಿಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    downloadorEditReport: "ನೀವು ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಅಥವಾ ಅದನ್ನು ಸಂಪಾದಿಸಲು ಬಯಸುವಿರಾ?",
    reportRetrievalError: "ನಿಮ್ಮ ವರದಿಯನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
    editReportText: "*ನಿಮ್ಮ ವರದಿಯನ್ನು ಸಂಪಾದಿಸಿ",
    discussionRecorded: "ನಿಮ್ಮ ಚರ್ಚೆ ಅಥವಾ ಕಥೆಯನ್ನು ದಾಖಲಿಸಲಾಗಿದೆ!",
    uploadLimit: "ನೀವು ಇಷ್ಟು ಅಪ್‌ಲೋಡ್ ಮಾಡಬಹುದು",
    yesUpload: "ಹೌದು, ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    evidenceLimit: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಫೋಟೋಗಳನ್ನು ಒಂದೊಂದಾಗಿ ಕಳುಹಿಸಿ (10 ರವರೆಗೆ).",
    done: "ಅಪ್‌ಲೋಡ್ ಮಾಡುವುದನ್ನು ಮುಗಿಸಿದಾಗ *done* ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    requestNextPhoto: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಮುಂದಿನ ಫೋಟೋವನ್ನು ಕಳುಹಿಸಿ.",
    lostSession: "ಸೆಷನ್ ಕಳೆದುಹೋಗಿದೆ. ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಲು ದಯವಿಟ್ಟು 'Hi' ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    cancelEvidenceUpload: "ಪುರಾವೆ ಅಪ್‌ಲೋಡ್ ಅನ್ನು ರದ್ದುಗೊಳಿಸಿ",
    cancelSession: "ರದ್ದುಗೊಳಿಸಲಾಗಿದೆ. ಆಯ್ಕೆಗಳನ್ನು ನೋಡಲು 'menu' ಎಂದು ಟೈಪ್ ಮಾಡಿ.",
    sessionLost: "ನಿಮ್ಮ ಸೆಷನ್‌ಗೆ ಮರುಸಂಪರ್ಕಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮುಖ್ಯ ಮೆನುಗೆ ಹಿಂತಿರುಗಲಾಗುತ್ತಿದೆ.",
    newSessionStarted: "ಹಿಂದಿನ ಸೆಷನ್ ಅನ್ನು ತೆರವುಗೊಳಿಸಲಾಗಿದೆ. ಹೊಸ ಸೆಷನ್ ಪ್ರಾರಂಭಿಸಲಾಗುತ್ತಿದೆ...",
    imageUploadFailed: "ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
    whatsappNotSupported: "ಕ್ಷಮಿಸಿ, ನಾನು ಕೇವಲ ಪಠ್ಯ, ಧ್ವನಿ, ಚಿತ್ರಗಳು ಮತ್ತು ಸಂವಾದಾತ್ಮಕ ಸಂದೇಶಗಳನ್ನು ಮಾತ್ರ ನಿಭಾಯಿಸಬಲ್ಲೆ",
    notUnderstood: "ಕ್ಷಮಿಸಿ, ಅದು ಅರ್ಥವಾಗಲಿಲ್ಲ. ಆಯ್ಕೆಗಳನ್ನು ನೋಡಲು ದಯವಿಟ್ಟು 'Hi' ಎಂದು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮುಖ್ಯ ಮೆನು ನೋಡಲು 'Menu' ಟೈಪ್ ಮಾಡಿ.",
    audioDownloadError: "ಆಡಿಯೊವನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ.",
    wsSessionRequired: "ಸಕ್ರಿಯ ಸೆಷನ್‌ನಲ್ಲಿರುವಾಗ ದಯವಿಟ್ಟು ಪಠ್ಯ/ಆಡಿಯೊದೊಂದಿಗೆ ಪ್ರತಿಕ್ರಿಯಿಸಿ.",
    voiceProcessing: "ನಿಮ್ಮ ಧ್ವನಿ ಸಂದೇಶವನ್ನು ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    voiceHeard: "ನಾನು ಕೇಳಿಸಿಕೊಂಡೆ:",
    voiceSendConfirm: "ಈ ಸಂದೇಶವನ್ನು ಕಳುಹಿಸಬೇಕೆ?",
    voiceEditPrompt: "✏️ ನಿಮ್ಮ ತಿದ್ದಿದ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ:",
    voiceRetryPrompt: "🔄 ದಯವಿಟ್ಟು ನಿಮ್ಮ ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಮತ್ತೊಮ್ಮೆ ಕಳುಹಿಸಿ.",
    voiceSend: "✅ ಕಳುಹಿಸಿ",
    voiceEdit: "✏️ ಸಂಪಾದಿಸಿ",
    voiceRetry: "🔄 ಮರುಪ್ರಯತ್ನಿಸಿ",
    voiceSent: "ಸಂದೇಶವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಕಳುಹಿಸಲಾಗಿದೆ.",
    voiceSendFailed: "ಸಂದೇಶವನ್ನು ಕಳುಹಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಪುನಃ ಪ್ರಯತ್ನಿಸಿ.",
    voiceNoPending: "ಯಾವುದೇ ಬಾಕಿ ಉಳಿದಿರುವ ಸಂದೇಶ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಮತ್ತೊಮ್ಮೆ ಕಳುಹಿಸಿ.",
    voiceNoTranscript: "ಸಂಪಾದಿಸಲು ಯಾವುದೇ ನಕಲು (ಟ್ರಾನ್ಸ್ಕ್ರಿಪ್ಟ್) ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಮತ್ತೊಮ್ಮೆ ಕಳುಹಿಸಿ.",
    languageSetup: "⏳ ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ..."
  },
  hi: {
    conversationStartMessage: "स्वागत है! मैं मित्रा हूँ, और मैं आपकी सुधार की कहानी इकट्ठा करने के लिए यहाँ हूँ। मैंने सुना है कि आपने और आपके समुदाय ने कुछ अद्भुत काम किया है, और मैं इसके बारे में सुनना चाहूँगा। शुरू करने के लिए, क्या आप मुझे अपना नाम बता सकते हैं?",
    conversationStartMessageForCaptureDiscussion: "स्वागत है! मैं मित्रा हूँ, और मैं आपकी चर्चाओं से महत्वपूर्ण बिंदुओं को कैप्चर करने के लिए यहाँ हूँ। मुझे पता है कि आपने और आपके समुदाय ने मूल्यवान विचार साझा किए हैं—चुनौतियाँ और समाधान दोनों। शुरू करने से पहले, क्या आप मुझे अपना नाम बता सकते हैं?",
    sessionReconnected: "सत्र फिर से जुड़ गया है! कृपया वहीं से जारी रखें जहाँ आपने छोड़ा था।",
    noPreviousSession: "आपका पिछला सत्र नहीं मिला। कृपया 'Hi' लिखकर नया सत्र शुरू करें।",
    errorMessage: "⚠️ कुछ गलत हो गया। फिर से शुरू करने के लिए 'Hi' टाइप करें।",
    sessionDiscontinue: "⚠️ आपका सत्र डिस्कनेक्ट हो गया था।",
    reconnectMessage: "क्या आप अपने मौजूदा सत्र से *फिर से जुड़ना* चाहेंगे या एक *नया* शुरू करना चाहेंगे?",
    inactiveSession: "आपका सत्र कुछ समय से निष्क्रिय है",
    reconnectPrompt: "क्या आप अपना वर्तमान सत्र *जारी रखना* चाहेंगे या *नया शुरू करना* चाहेंगे?",
    sessionCompleted: "बधाई हो! आपने अपना सत्र पूरा कर लिया है। नया सत्र शुरू करने के लिए 'Hi' टाइप करें।",
    maxPhotosWarning: "आप अनुमत फ़ोटो की अधिकतम संख्या तक पहुँच गए हैं",
    doneMessage: "अपनी रिपोर्ट तैयार करने के लिए *done* टाइप करें",
    imageDownloadError: "छवि डाउनलोड नहीं की जा सकी। कृपया पुनः प्रयास करें।",
    storyDownloadError: "आपकी कहानी प्राप्त नहीं की जा सकी। कृपया पुनः प्रयास करें।",
    imageUploadSuccess: "छवि सफलतापूर्वक अपलोड हो गई!",
    remainingPhotos: "फ़ोटो शेष हैं। आप और फ़ोटो/वीडियो भेज सकते हैं या अभी समाप्त कर सकते हैं..",
    addMorePhotos: "और फ़ोटो/वीडियो जोड़ें",
    reportGenerationMessage: "फ़ोटो अपलोड हो गईं! आपकी रिपोर्ट तैयार की जा रही है...",
    downloadorEditReport: "क्या आप रिपोर्ट डाउनलोड करना चाहेंगे या इसे संपादित करना चाहेंगे?",
    reportRetrievalError: "आपकी रिपोर्ट प्राप्त नहीं की जा सकी। कृपया पुनः प्रयास करें।",
    editReportText: "*अपनी रिपोर्ट संपादित करें",
    discussionRecorded: "आपकी चर्चा या कहानी रिकॉर्ड कर ली गई है!",
    uploadLimit: "आप यहाँ तक अपलोड कर सकते हैं",
    yesUpload: "हाँ, अपलोड करें",
    evidenceLimit: "कृपया अपनी फ़ोटो एक-एक करके भेजें (अधिकतम 10)।",
    done: "अपलोडिंग समाप्त करने पर *done* टाइप करें।",
    requestNextPhoto: "कृपया अपनी अगली फ़ोटो भेजें।",
    lostSession: "सत्र समाप्त हो गया। फिर से शुरू करने के लिए कृपया 'Hi' टाइप करें।",
    cancelEvidenceUpload: "साक्ष्य अपलोड रद्द करें",
    cancelSession: "रद्द कर दिया गया। विकल्प देखने के लिए 'menu' टाइप करें।",
    sessionLost: "आपके सत्र से फिर से नहीं जुड़ सका। मुख्य मेनू पर लौट रहे हैं।",
    newSessionStarted: "पिछला सत्र साफ़ हो गया। नया सत्र शुरू किया जा रहा है...",
    imageUploadFailed: "छवि अपलोड करने में विफल। कृपया पुनः प्रयास करें।",
    whatsappNotSupported: "क्षमा करें, मैं केवल टेक्स्ट, वॉइस, चित्र और इंटरैक्टिव संदेश ही संभाल सकता हूँ",
    notUnderstood: "क्षमा करें, वह समझ में नहीं आया। कृपया विकल्प देखने के लिए 'Hi' या मुख्य मेनू देखने के लिए 'Menu' टाइप करें।",
    audioDownloadError: "ऑडियो डाउनलोड नहीं किया जा सका। कृपया अपना उत्तर टाइप करें।",
    wsSessionRequired: "कृपया सक्रिय सत्र के दौरान टेक्स्ट/ऑडियो के साथ उत्तर दें।",
    voiceProcessing: "आपके ध्वनि संदेश को प्रोसेस किया जा रहा है...",
    voiceHeard: "मैंने सुना:",
    voiceSendConfirm: "क्या यह संदेश भेजें?",
    voiceEditPrompt: "✏️ अपना सही किया हुआ संदेश टाइप करें:",
    voiceRetryPrompt: "🔄 कृपया अपना वॉइस नोट दोबारा भेजें।",
    voiceSend: "✅ भेजें",
    voiceEdit: "✏️ संपादित करें",
    voiceRetry: "🔄 पुनः प्रयास करें",
    voiceSent: "संदेश सफलतापूर्वक भेजा गया।",
    voiceSendFailed: "संदेश भेजने में विफल। कृपया पुनः प्रयास करें।",
    voiceNoPending: "कोई लंबित संदेश नहीं मिला। कृपया अपना वॉइस नोट दोबारा भेजें।",
    voiceNoTranscript: "संपादित करने के लिए कोई ट्रांसक्रिप्ट नहीं मिली। कृपया अपना वॉइस नोट दोबारा भेजें।",
    languageSetup: "⏳ आपकी भाषा सेट की जा रही है..."
  },
  te: {
    conversationStartMessage: "స్వాగతం! నేను మిత్ర, మరియు నేను మీ అభివృద్ధి కథను సేకరించడానికి ఇక్కడ ఉన్నాను. మీరు మరియు మీ సంఘం కొన్ని అద్భుతమైన పనులు చేశారని నేను విన్నాను, దాని గురించి వినడానికి నేను ఆసక్తిగా ఉన్నాను. ప్రారంభించడానికి, దయచేసి మీ పేరు చెప్పగలరా?",
    conversationStartMessageForCaptureDiscussion: "స్వాగతం! నేను మిత్ర, మీ చర్చల నుండి ముఖ్యమైన అంశాలను రికార్డ్ చేయడానికి నేను ఇక్కడ ఉన్నాను. మీరు మరియు మీ సంఘం సవాళ్లు మరియు పరిష్కారాలు రెండింటిపై విలువైన అంతర్దృష్టులను పంచుకున్నారని నాకు తెలుసు. మనం ప్రారంభించడానికి ముందు, దయచేసి మీ పేరు చెప్పగలరా?",
    sessionReconnected: "సెషన్ మళ్లీ కనెక్ట్ చేయబడింది! దయచేసి మీరు ఎక్కడ ఆపారో అక్కడి నుండి కొనసాగించండి.",
    noPreviousSession: "మీ మునుపటి సెషన్ కనుగొనబడలేదు. దయచేసి 'Hi' అని టైప్ చేయడం ద్వారా కొత్తదాన్ని ప్రారంభించండి.",
    errorMessage: "⚠️ ఏదో తప్పు జరిగింది. మళ్లీ ప్రారంభించడానికి 'Hi' అని టైప్ చేయండి.",
    sessionDiscontinue: "⚠️ మీ సెషన్ డిస్‌కనెక్ట్ చేయబడింది.",
    reconnectMessage: "మీరు మీ ప్రస్తుత సెషన్‌కి *మళ్లీ కనెక్ట్ చేయాలనుకుంటున్నారా* లేదా *కొత్తది* ప్రారంభించాలనుకుంటున్నారా?",
    inactiveSession: "మీ సెషన్ కొంత కాలంగా నిష్క్రియంగా ఉంది",
    reconnectPrompt: "మీరు మీ ప్రస్తుత సెషన్‌ను *కొనసాగించాలనుకుంటున్నారా* లేదా *కొత్తది ప్రారంభించాలనుకుంటున్నారా*?",
    sessionCompleted: "అభినందనలు! మీరు మీ సెషన్‌ను పూర్తి చేసారు. కొత్తదాన్ని ప్రారంభించడానికి 'Hi' అని టైప్ చేయండి.",
    maxPhotosWarning: "మీరు అనుమతించబడిన గరిష్ట ఫొటోల సంఖ్యను చేరుకున్నారు",
    doneMessage: "మీ నివేదికను రూపొందించడానికి *done* అని టైప్ చేయండి",
    imageDownloadError: "చిత్రాన్ని డౌన్‌లోడ్ చేయడం సాధ్యపడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
    storyDownloadError: "మీ కథనాన్ని తిరిగి పొందడం సాధ్యపడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
    imageUploadSuccess: "చిత్రం విజయవంతంగా అప్‌లోడ్ చేయబడింది!",
    remainingPhotos: "ఫోటో(లు) మిగిలి ఉన్నాయి. మీరు మరిన్ని ఫోటోలు/వీడియోలను పంపవచ్చు లేదా ఇప్పుడు ముగించవచ్చు..",
    addMorePhotos: "మరిన్ని ఫోటోలు/వీడియోలను జోడించండి",
    reportGenerationMessage: "ఫోటోలు అప్‌లోడ్ చేయబడ్డాయి! మీ నివేదిక రూపొందించబడుతోంది...",
    downloadorEditReport: "మీరు నివేదికను డౌన్‌లోడ్ చేయాలనుకుంటున్నారా లేదా దాన్ని సవరించాలనుకుంటున్నారా?",
    reportRetrievalError: "మీ నివేదికను తిరిగి పొందడం సాధ్యపడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.",
    editReportText: "*మీ నివేదికను సవరించండి",
    discussionRecorded: "మీ చర్చ లేదా కథనం రికార్డ్ చేయబడింది!",
    uploadLimit: "మీరు గరిష్టంగా అప్‌లోడ్ చేయవచ్చు",
    yesUpload: "అవును, అప్‌లోడ్ చేయండి",
    evidenceLimit: "దయచేసి మీ ఫోటోలను ఒక్కొక్కటిగా పంపండి (10 వరకు).",
    done: "అప్‌లోడ్ చేయడం పూర్తి చేసినప్పుడు *done* అని టైప్ చేయండి.",
    requestNextPhoto: "దయచేసి మీ తదుపరి ఫోటోను పంపండి.",
    lostSession: "సెషన్ కోల్పోయింది. మళ్లీ ప్రారంభించడానికి దయచేసి 'Hi' అని టైప్ చేయండి.",
    cancelEvidenceUpload: "ఆధారం అప్‌లోడ్ రద్దు చేయండి",
    cancelSession: "రద్దు చేయబడింది. ఎంపికలను చూడటానికి 'menu' అని టైప్ చేయండి.",
    sessionLost: "మీ సెషన్‌కి మళ్లీ కనెక్ట్ చేయడం సాధ్యపడలేదు. ప్రధాన మెనూకి తిరిగి వెళుతోంది.",
    newSessionStarted: "మునుపటి సెషన్ క్లియర్ చేయబడింది. కొత్త సెషన్ ప్రారంభమవుతోంది...",
    imageUploadFailed: "చిత్రాన్ని అప్‌లోడ్ చేయడం విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    whatsappNotSupported: "క్షమించండి, నేను టెక్స్ట్, వాయిస్, చిత్రాలు మరియు ఇంటరాక్టివ్ సందేశాలను మాత్రమే నిర్వహించగలను",
    notUnderstood: "క్షమించండి, నాకు అది అర్థం కాలేదు. దయచేసి ఎంపికలను చూడటానికి 'Hi' అని లేదా ప్రధాన మెనూని చూడటానికి 'Menu' అని టైప్ చేయండి.",
    audioDownloadError: "ఆడియోను డౌన్‌లోడ్ చేయడం సాధ్యపడలేదు. దయచేసి మీ ప్రతిస్పందనను టైప్ చేయండి.",
    wsSessionRequired: "దయచేసి యాక్టివ్ సెషన్ సమయంలో టెక్స్ట్/ఆడియోతో ప్రతిస్పందించండి.",
    voiceProcessing: "మీ వాయిస్ సందేశం ప్రాసెస్ చేయబడుతోంది...",
    voiceHeard: "నేను విన్నాను:",
    voiceSendConfirm: "ఈ సందేశాన్ని పంపాలా?",
    voiceEditPrompt: "✏️ మీ సరిదిద్దబడిన సందేశాన్ని టైప్ చేయండి:",
    voiceRetryPrompt: "🔄 దయచేసి మీ వాయిస్ నోట్‌ను మళ్లీ పంపండి.",
    voiceSend: "✅ పంపండి",
    voiceEdit: "✏️ సవరించండి",
    voiceRetry: "🔄 మళ్లీ ప్రయత్నించండి",
    voiceSent: "సందేశం విజయవంతంగా పంపబడింది.",
    voiceSendFailed: "సందేశం పంపడం విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.",
    voiceNoPending: "పెండింగ్‌లో ఉన్న సందేశం ఏదీ కనుగొనబడలేదు. దయచేసి మీ వాయిస్ నోట్‌ను మళ్లీ పంపండి.",
    voiceNoTranscript: "సవరించడానికి ట్రాన్స్‌క్రిప్ట్ ఏదీ కనుగొనబడలేదు. దయచేసి మీ వాయిస్ నోట్‌ను మళ్లీ పంపండి.",
    languageSetup: "⏳మీ భాషను సెటప్ చేస్తోంది..."
  }
};

module.exports = LANGUAGE_MESSAGE;
